### ISSUE TITLE
i want to konw how to start env and ppo.py?

### ISSUE THREAD

**Issue by Lovemyse1f** [Tortes/RLNavigation#1]
@Tortes hi , i'm very glad that you can open project, and i have also integrated tianshou and gym-gazebo. But i have met some errors that i didn't solve. Luckily, i met your answer in tianshou. But i don't know how to run the trainer. 
If you're  free,  can you help me look these errors flowing? 

the following errors were happened when my project has been run for a moment:
1.
gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::transport::CallbackHelper; typename boost::detail::sp_member_access<T>::type = gazebo::transport::CallbackHelper*]: Assertion `px != 0' failed.
Aborted (core dumped)
2.Segmentation fault (core dumped)
[gazebo-2] process has died [pid 26305, exit code 139, cmd /home//gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gzserver --verbose -e ode /home//gym-gazebo/gym_gazebo/envs/installation/../assets/worlds/circuit2.world __name:=gazebo __log:=/home//.ros/log/9c31ed50-f71a-11ea-8290-fd7b51fc756d/gazebo-2.log].
log file: /home//.ros/log/9c31ed50-f71a-11ea-8290-fd7b51fc756d/gazebo-2*.log

**Comment by Tortes** [comment]
Firstly, my environment is based on the Ubuntu16.04 and ROS Kinetic. Then, you should make sure that the version of gazebo is 7.  For the simulation environment, I just tested with the [turtlebot stages 1~4](https://github.com/ROBOTIS-GIT/turtlebot3_simulations/tree/master/turtlebot3_gazebo/worlds). The segmentation fault may be caused by stack overflows. Now my code is just under test and I have no prepare for a proper result. You could refer to [this repo](https://github.com/m5823779/MotionPlannerUsingDDPG) for a 2d navigation practise.
